List<dynamic> categories = [
  {
    "id": 1,
    "title": "E",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 1",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 2,
    "title": "x",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 2",
    "imageUrl": "assets/images/02.jpg",
  },
  {
    "id": 3,
    "title": "e",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 1",
    "imageUrl": "assets/images/03.jpg",
  },
  {
    "id": 4,
    "title": "x",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 2",
    "imageUrl": "assets/images/04.jpg",
  },
  {
    "id": 5,
    "title": "Ea",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 1",
    "imageUrl": "assets/images/05.jpg",
  },
  {
    "id": 6,
    "title": "Ex",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 2",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 7,
    "title": "vitamine",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 1",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 8,
    "title": "appariel",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 2",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 9,
    "title": "vetement",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 1",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 10,
    "title": "pommede2",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "vitamine",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 11,
    "title": "pommede1",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 1",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 12,
    "title": "pommede2",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 2",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 13,
    "title": "pommede1",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "Example Value 1",
    "imageUrl": "assets/images/06.jpg",
  },
  {
    "id": 14,
    "title": "more",
    "rating": " toop,",
    "price": "10.00 DA",
    "value": "More",
    "imageUrl": "assets/images/R.jpg",
  },
];
